# Workshop 2

## Install lockdown browser

### Getting around with the shell

## Install Anaconda

### Introduction to the IPython CLI

### Introduction to Jupyter Notebooks

1. Change Filename
2. Menubar
3. Toolbar
4. Mode Indicator: Command and Edit (green border around active cell)
5. Kernal Indicator (busy or idle circle)
6. Interrupt the Kernal
7. Notification Area top right of menu bar
8. Code and Markdown
9. Markdown is a subset of HTML: <a href="https://daringfireball.net/projects/markdown/basics">Markdown help</a>
10. <a href="https://www.dataquest.io/blog/jupyter-notebook-tips-tricks-shortcuts/">Jupyter Notebook Tips and Tricks</a>

## Hello World

UNIX users are already familiar with the concept of standard input, standard output, and standard error. This section is for the rest of you.

Standard output and standard error (commonly abbreviated stdout and stderr) are pipes that are built into every UNIX system. When you print something, it goes to the stdout pipe; when your program crashes and prints out debugging information (like a traceback in Python), it goes to the stderr pipe. Both of these pipes are ordinarily just connected to the terminal window where you are working, so when a program prints, you see the output, and when a program crashes, you see the debugging information. (If you're working on a system with a window-based Python IDE, stdout and stderr default to your “Interactive Window”.)

In [1]:
### Functions: func()
print("Hello World")

Hello World


In [2]:
help(print)
print?

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



In [3]:
### Python Calculator
print(3 + 2) #result integer
print(3 * 2)
print(6 / 3) #result float
print("Squareroot of 64 = ", 64 ** 0.5) #result float
print("Cube root of 8 = ", 8 ** (1/3))
print(100 % 27) #modulus returns remainder part of quotient
print(100 // 27) #floor division returns integer part of quotient

5
6
2.0
Squareroot of 64 =  8.0
Cube root of 8 =  2.0
19
3


### Identifiers
Names of variables, objects, functions, methods, classes, etc.
1. Identifiers can be a combination of letters in lowercase (a to z) or uppercase (A to Z) or digits (0 to 9) or an underscore (_). 
2. Names like myClass, var_1 and print_this_to_screen, all are valid example.
3. An identifier cannot start with a digit. 1variable is invalid, but variable1 is perfectly fine.
4. Keywords cannot be used as identifiers.

### Statements
Statements are instructions to the computer. 
1. Usually consists of a keyword verb and an object upon which the command is acting
2. Assignments are also statements
2. Most statements are one-line, some are multi-line
    1-line: x = 5
    multi-line:
        x = 4 + 3 \
            5 + 7 \
            12 + 6
            
        y = (2 + 1
             4 + 4)
        
        z = ["small",
            "medium",
            "large"]
3. Multiple statements on one line separated by semi-colons (poor style):
    x = 5; y = 6; z = 8

### Variables and their Types
Classes and objects are the two main aspects of object oriented programming. A class creates a new type where objects are instances of the class. An analogy is that you can have variables of type <i>int</i> which translates to saying that variables that store integers are variables which are instances (objects) of the <i>int</i> class. Variables are containers for data. As objects, they also have methods associated with them according to what class they belong. 

#### Numeric types
int, float, complex

In [4]:
x = 5
print(type(x))

<class 'int'>


In [5]:
y = 3.0
print(type(y))

<class 'float'>


#### Sequences

Sequences are objects that contain other objects. Sequences come in four types: text, lists, tuples and sets.

Text (aka string)

In [6]:
firstVar = "this is a string."
print(type(firstVar))

<class 'str'>


Indexing

In [7]:
firstVar[3]

's'

In [8]:
firstVar[1:7]

'his is'

In [9]:
firstVar[0:7]

'this is'

In [10]:
firstVar[:7]

'this is'

In [11]:
firstVar[3:17]

's is a string.'

In [12]:
len(firstVar)

17

In [13]:
firstVar[-10:16]

' a string'

In [14]:
firstVar[-10:17]

' a string.'

In [15]:
firstVar[-10:len(firstVar)]

' a string.'

In [16]:
max(firstVar)

't'

Apply the method "capitalize" to the string object firstVar. Note that a method is applied with a dot notation: <i>object</i>.<i>method(arg)</i>

In [17]:
firstVar.capitalize()

'This is a string.'

Concatenate firstVar

In [18]:
firstVar = firstVar + ' This one is too.'
print(firstVar)

this is a string. This one is too.


In [19]:
firstVar = firstVar[:17]
print(firstVar)

this is a string.


#### List

A list is a collection of objects that can be of any type, even other lists.

In [20]:
firstList = [1, 5, 8, 13]
print(firstList)
print(type(firstList))

[1, 5, 8, 13]
<class 'list'>


Like strings, the members of lists are indexed.

In [21]:
print(firstList[1:3])

[5, 8]


Notice that the index starts at 0 and that the end of the slice excludes that member.

In [22]:
print(firstList[0])

1


Add elements to a list with the <i>extend</i> method:

In [23]:
firstList.extend([15, 21])
print(firstList)

[1, 5, 8, 13, 15, 21]


Search a list for the index of an element and then change it to 14:

In [24]:
firstList.index(15)

4

In [25]:
firstList[4] = 14
firstList

[1, 5, 8, 13, 14, 21]

In [26]:
firstList.extend(["a", "b", "c"])
print(firstList)


[1, 5, 8, 13, 14, 21, 'a', 'b', 'c']


Delete an element from a list:

In [27]:
firstList.remove(21)
firstList

[1, 5, 8, 13, 14, 'a', 'b', 'c']

Insert an element:

In [28]:
firstList.insert(5, 21)
firstList

[1, 5, 8, 13, 14, 21, 'a', 'b', 'c']

In [29]:
secondList = firstList * 2
secondList

[1, 5, 8, 13, 14, 21, 'a', 'b', 'c', 1, 5, 8, 13, 14, 21, 'a', 'b', 'c']

Here is an example of lists within a list:

In [30]:
thirdList = [firstList, "e", "f", "g", [8, 9, 10]]
print(thirdList)

[[1, 5, 8, 13, 14, 21, 'a', 'b', 'c'], 'e', 'f', 'g', [8, 9, 10]]


#### Tuple

Tuples are sequences of heterogeneous type.

In [31]:
firstTuple = (2, 4, 8, 19)
type(firstTuple)

tuple

In [32]:
print(firstTuple[0:2])

(2, 4)


In [33]:
print(firstTuple * 2)

(2, 4, 8, 19, 2, 4, 8, 19)


Tuples are immutable, meaning that the elements cannot be changed.

In [34]:
firstTuple[3] = 5

TypeError: 'tuple' object does not support item assignment

#### Set

Sets are unordered collections of objects.

In [36]:
firstSet = set(["milk", "eggs", "rice"])
print(type(firstSet))
print(firstSet)

<class 'set'>
{'rice', 'milk', 'eggs'}


In [37]:
"milk" in firstSet

True

#### Dictionary

A dictionary is a mapping object, that is, it is a collection of objects that are associated (mapped) with other objects in a one-to-one or many-to-one fashion. They can be used as lookup tables.

In [38]:
firstDict = {
   "eggs":"dairy",
   "bread":"bakery",
   "lettuce":"produce",
   "milk":"dairy"
}

Discover what keys are available in firstDict with the <i>keys</i> method:

In [39]:
firstDict.keys()

dict_keys(['eggs', 'bread', 'lettuce', 'milk'])

To which category do eggs belong?

In [40]:
print(firstDict["eggs"])

dairy


Add a key:value pair to a dictionary

In [43]:
firstDict["butter"] = "dairy"
print(firstDict)

{'eggs': 'dairy', 'bread': 'bakery', 'lettuce': 'produce', 'milk': 'dairy', 'butter': 'dairy'}


Remove a key:value pair

In [46]:
del(firstDict["butter"])
print (firstDict)

{'eggs': 'dairy', 'bread': 'bakery', 'lettuce': 'produce', 'milk': 'dairy'}


It is also possible to assign multiple values to a key. Think of these as dictionaries within dictionaries.

In [48]:
secondDict = {"Tokyo": {"density": "high", "cost of living": "high", "smog": "yes"}, 
              "Wyoming": {"density": "low", "cost of living": "low", "smog": "no"} }

Use double square brackets to extract elements.

In [55]:
print(secondDict["Tokyo"]["smog"])

yes


#### Boolean

The boolean type is named after the English mathematician George Boole who invented boolean algebra in 1854.

Boolean objects have one of two values: True or False. We have already seen an example of a boolean in the dictionary lookup above. They are used to make comparisons. Remember the "L" in the computer CPU's "ALU"? Let's see how they work and discover the strange behavior of boolean logic.

In [183]:
x = 5
y = 10
print(x < y)

True


In [184]:
x > y

False

In [185]:
x == y #Note the use of the double "=="

False

In [186]:
x <= y

True

OR and AND

In [187]:
x > y or x < 6

True

In [196]:
x > 4 and y < 20

True

The machine language representation of booleans is 0 for False and 1 for True.

In [188]:
4 > 1 + 6

False

In [189]:
(4 > 1) + 6

7

In [190]:
type(3 <= 10)

bool

In [198]:
z = (x < 10)
print(z)

True


In [199]:
z != False

True

### Flow Control

The utility of boolean comparisons becomes apparent when we want to control the operation of our programs. We'll want some parts of our program to execute if certain conditions are met and other parts to execute if those conditions are not met. We may even want the execution of our program to halt.

if

In [191]:
x = 6
if x == 6 :
    print("This is the correct answer.")

This is the correct answer.


In [192]:
x = 7
if x == 6 :
    print("This is the correct answer.")
else : print("This is not correct.")

This is not correct.


In [193]:
x == 6

False

In [194]:
condition = (x == 6)
print(condition)

if condition :
    print("This is the correct answer.")
else : print("This is not correct.")    

False
This is not correct.


Add elif

In [195]:
condition = (x == 6)
print(condition)

if condition :
    print("This is the correct answer.")
elif x > 6 :
    print("Maybe correct.")
else : 
    print("This is not correct.")    

False
Maybe correct.


### Loops

Loops are used to execute python statements in a repeated fashion. Loops come in two flavors: <b>while</b> loops and <b>for</b> loops. <b>While</b> loops iterate as long as a condition exists. <b>For</b> loops iterate over a sequence such as a list or index.

In [60]:
i = 1
while i <= 4:
    print(i)
    i = i + 1

1
2
3
4


<b>For</b> loops have this form:

For <i>var</i> in <i>seq</i>:
<p style="text-indent: 40px">statements</p>

In [66]:
print (firstList)
for stuff in firstList:
    print(stuff * 2)

[1, 5, 8, 13, 14, 21, 'a', 'b', 'c']
2
10
16
26
28
42
aa
bb
cc


Iterate over a slice of the sequence.

In [67]:
for stuff in firstList[0:3]:
    print(stuff)


1
5
8


We can also include <b>if</b> statements.

In [71]:
for stuff in firstList[:6]:
    if stuff < 14:
        print(stuff)

1
5
8
13


### Modules and Packages

Python functions and object class definitions are bundled together in <b>modules</b>. Modules in turn are often distributed in <b>packages</b>. These packages are made available through private and public repositories. The largest and most widely used repository of python packages is <b>PyPi</b>, the Python Package Index (https://pypi.python.org/pypi).

To use a  module from any of these packages the package must first be <i>installed</i> and then the module must be <i>imported</i> into the current session.

Many of the most commonly used packages are already installed when you installed the Anaconda distribution of Python. These include <b>csv</b>, a packaged used to read in the most commonly used data file format, <b>NumPy</b>, a package that contains functions and class templates for objects useful to data science such as numeric arrays, and <b>Pandas</b>, a package that is used for a Python data structure called <i>Data Frames</i>. Another popular package is <b>MatPlotLib</b>, used to produce charts and other data visualizations.

In [73]:
import csv

In [1]:
with open('C:/Users/Tim/Google Drive/SMU/ITOM 6267 Data Mining MSBA/data/iris.csv', newline='') as myFile:  
    reader = list(csv.reader(myFile))
    print(type(reader))
    for row in reader[0:5]:
        print(row)

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/Tim/Google Drive/SMU/ITOM 6267 Data Mining MSBA/data/iris.csv'

In [1]:
import numpy as np

In [83]:
secondList = firstList[0:5]
print(secondList)
print(type(secondList))

[1, 5, 8, 13, 14]
<class 'list'>


In [84]:
thirdList = secondList * 2
print(thirdList)

[1, 5, 8, 13, 14, 1, 5, 8, 13, 14]


In [87]:
np_thirdList = np.array(thirdList[0:5])
print(np_thirdList)
print(type(np_thirdList))

[ 1  5  8 13 14]
<class 'numpy.ndarray'>


In [88]:
print(np_thirdList * 2)

[ 2 10 16 26 28]


In [2]:
a = np.array([[2,5,7],[4,3,7],[5,8,2],[4,4,5]])
b = np.array([[2,5,7,1],[4,3,7,5],[5,8,2,0]])
print(a)
print(a.ndim)
print(a.shape)
print(b)
print(b.ndim)
print(b.shape)

c = np.dot(a,b)
print(c)

[[2 5 7]
 [4 3 7]
 [5 8 2]
 [4 4 5]]
2
(4, 3)
[[2 5 7 1]
 [4 3 7 5]
 [5 8 2 0]]
2
(3, 4)
[[59 81 63 27]
 [55 85 63 19]
 [52 65 95 45]
 [49 72 66 24]]


In [93]:
import pandas as pd

In [94]:
iris = pd.read_csv('C:/Users/Tim/Google Drive/SMU/ITOM 6267 Data Mining MSBA/data/iris.csv')
print(type(iris))

<class 'pandas.core.frame.DataFrame'>


In [95]:
print(iris[0:5])

   Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           1           5.1          3.5           1.4          0.2  setosa
1           2           4.9          3.0           1.4          0.2  setosa
2           3           4.7          3.2           1.3          0.2  setosa
3           4           4.6          3.1           1.5          0.2  setosa
4           5           5.0          3.6           1.4          0.2  setosa


Note that the read_csv function read in a separate column "Unnamed" populated with the row labels. We can tell python to ignore those lables with the index_col = 0 argument:

In [96]:
iris = pd.read_csv('C:/Users/Tim/Google Drive/SMU/ITOM 6267 Data Mining MSBA/data/iris.csv', index_col = 0)
print(iris[0:5])

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
1           5.1          3.5           1.4          0.2  setosa
2           4.9          3.0           1.4          0.2  setosa
3           4.7          3.2           1.3          0.2  setosa
4           4.6          3.1           1.5          0.2  setosa
5           5.0          3.6           1.4          0.2  setosa
