In [1]:
import csv

with open("C:/Users/jhb_f/Desktop/Fall 2017 B/Programming/iris.csv", newline="") as myFile:  
    reader = list(csv.reader(myFile))
    print(type(reader))
    for row in reader[0:5]:
        print(row)

<class 'list'>
['', 'sepalLength', 'sepalWidth', 'petalLength', 'petalWidth', 'species']
['1', '5.1', '3.5', '1.4', '0.2', 'setosa']
['2', '4.9', '3', '1.4', '0.2', 'setosa']
['3', '4.7', '3.2', '1.3', '0.2', 'setosa']
['4', '4.6', '3.1', '1.5', '0.2', 'setosa']


In [5]:
irisList1 = reader[1:]
print(irisList1[0:5])

[['1', '5.1', '3.5', '1.4', '0.2', 'setosa'], ['2', '4.9', '3', '1.4', '0.2', 'setosa'], ['3', '4.7', '3.2', '1.3', '0.2', 'setosa'], ['4', '4.6', '3.1', '1.5', '0.2', 'setosa'], ['5', '5', '3.6', '1.4', '0.2', 'setosa']]


In [6]:
irisList2 = irisList1[0][1:5]
print(irisList2)

['5.1', '3.5', '1.4', '0.2']


In [7]:
irisList2[0] = list(irisList2)
del irisList2[1:4]
print(irisList2)

[['5.1', '3.5', '1.4', '0.2']]


In [9]:
foo = irisList1[1][1:5]
print(foo)

['4.9', '3', '1.4', '0.2']


In [10]:
irisList2.append(foo)
print(irisList2)

[['5.1', '3.5', '1.4', '0.2'], ['4.9', '3', '1.4', '0.2']]


In [14]:
for i in range(2, len(irisList1)):
    foo = irisList1[i][1:5]
    irisList2.append(foo)

print(irisList2[0:3])

[['5.1', '3.5', '1.4', '0.2'], ['4.9', '3', '1.4', '0.2'], ['4.7', '3.2', '1.3', '0.2']]


In [15]:
import numpy as np

In [16]:
np_iris = np.array(irisList2)
np_iris1 = np_iris.astype(np.float)
print(type(np_iris1))
print(np_iris1.shape)
print(np_iris1[:3, :])

<class 'numpy.ndarray'>
(150, 4)
[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]]


In [17]:
meanIris = np.mean(np_iris1, axis=0)
print(meanIris)

[ 5.84333333  3.05733333  3.758       1.19933333]


In [18]:
stdIris = np.std(np_iris1, axis=0)
print(stdIris)

[ 0.82530129  0.43441097  1.75940407  0.75969263]


In [4]:
import pandas as pd

In [5]:
iris = pd.read_csv("C:/Users/jhb_f/Desktop/Fall 2017 B/Programming/iris.csv", index_col=0)
print(type(iris))

<class 'pandas.core.frame.DataFrame'>


In [24]:
print(iris[0:5])

   sepalLength  sepalWidth  petalLength  petalWidth species
1          5.1         3.5          1.4         0.2  setosa
2          4.9         3.0          1.4         0.2  setosa
3          4.7         3.2          1.3         0.2  setosa
4          4.6         3.1          1.5         0.2  setosa
5          5.0         3.6          1.4         0.2  setosa


In [25]:
iris.sepalLength.mean()

5.843333333333335

In [27]:
speciesCount = iris['species'].value_counts(dropna=True)

virginica     50
versicolor    50
setosa        50
Name: species, dtype: int64

In [28]:
iris.sepalLength.agg(['count', 'mean', 'std'])

count    150.000000
mean       5.843333
std        0.828066
Name: sepalLength, dtype: float64

In [29]:
iris.groupby('species').sepalLength.agg(['count', 'mean', 'std'])

count   mean       std
species                           
setosa         50  5.006  0.352490
versicolor     50  5.936  0.516171
virginica      50  6.588  0.635880

In [30]:
iris.groupby('species').agg(['count', 'mean', 'std'])

sepalLength                  sepalWidth                   \
                 count   mean       std      count   mean       std   
species                                                               
setosa              50  5.006  0.352490         50  3.428  0.379064   
versicolor          50  5.936  0.516171         50  2.770  0.313798   
virginica           50  6.588  0.635880         50  2.974  0.322497   

           petalLength                  petalWidth                   
                 count   mean       std      count   mean       std  
species                                                              
setosa              50  1.462  0.173664         50  0.246  0.105386  
versicolor          50  4.260  0.469911         50  1.326  0.197753  
virginica           50  5.552  0.551895         50  2.026  0.274650

In [31]:
iris.groupby('species').agg(['count', 'mean', 'std', 'skew'])

sepalLength                            sepalWidth                   \
                 count   mean       std      skew      count   mean       std   
species                                                                         
setosa              50  5.006  0.352490  0.120087         50  3.428  0.379064   
versicolor          50  5.936  0.516171  0.105378         50  2.770  0.313798   
virginica           50  6.588  0.635880  0.118015         50  2.974  0.322497   

                     petalLength                            petalWidth         \
                skew       count   mean       std      skew      count   mean   
species                                                                         
setosa      0.041167          50  1.462  0.173664  0.106394         50  0.246   
versicolor -0.362845          50  4.260  0.469911 -0.606508         50  1.326   
virginica   0.365949          50  5.552  0.551895  0.549445         50  2.026   

                                
                 std      skew  
species                         
setosa      0.105386  1.253861  
versicolor  0.197753 -0.031180  
virginica   0.274650 -0.129477

In [34]:
irisVersicolor = iris.loc[iris.species == 'versicolor']
print(irisVersicolor.head(5))

    sepalLength  sepalWidth  petalLength  petalWidth     species
51          7.0         3.2          4.7         1.4  versicolor
52          6.4         3.2          4.5         1.5  versicolor
53          6.9         3.1          4.9         1.5  versicolor
54          5.5         2.3          4.0         1.3  versicolor
55          6.5         2.8          4.6         1.5  versicolor


In [36]:
irisVersicolor = iris.loc[0:3, :]
print(irisVersicolor.head(5))

   sepalLength  sepalWidth  petalLength  petalWidth species
1          5.1         3.5          1.4         0.2  setosa
2          4.9         3.0          1.4         0.2  setosa
3          4.7         3.2          1.3         0.2  setosa


In [37]:
irisVersicolor = iris.iloc[0:3, :]
print(irisVersicolor.head(5))

   sepalLength  sepalWidth  petalLength  petalWidth species
1          5.1         3.5          1.4         0.2  setosa
2          4.9         3.0          1.4         0.2  setosa
3          4.7         3.2          1.3         0.2  setosa


In [38]:
iris = pd.read_csv("C:/Users/jhb_f/Desktop/Fall 2017 B/Programming/iris.csv", index_col='species')
print(iris.head(5))

         Unnamed: 0  sepalLength  sepalWidth  petalLength  petalWidth
species                                                              
setosa            1          5.1         3.5          1.4         0.2
setosa            2          4.9         3.0          1.4         0.2
setosa            3          4.7         3.2          1.3         0.2
setosa            4          4.6         3.1          1.5         0.2
setosa            5          5.0         3.6          1.4         0.2


In [40]:
iris.count()

Unnamed: 0     150
sepalLength    150
sepalWidth     150
petalLength    150
petalWidth     150
dtype: int64

In [42]:
irisSetosa = iris.loc['setosa', 'sepalLength' : 'petalWidth']
print(irisSetosa.head(5))

         sepalLength  sepalWidth  petalLength  petalWidth
species                                                  
setosa           5.1         3.5          1.4         0.2
setosa           4.9         3.0          1.4         0.2
setosa           4.7         3.2          1.3         0.2
setosa           4.6         3.1          1.5         0.2
setosa           5.0         3.6          1.4         0.2


In [43]:
iris = pd.read_csv("C:/Users/jhb_f/Desktop/Fall 2017 B/Programming/iris_missing.csv", index_col='species')
print(iris.head(10))


         rowId  sepalLength  sepalWidth  petalLength  petalWidth
species                                                         
setosa       1          5.1         3.5          1.4         0.2
setosa       2          4.9         3.0          1.4         0.2
setosa       3          4.7         3.2          1.3         0.2
setosa       4          4.6         3.1          1.5         0.2
setosa       5          5.0         3.6          1.4         0.2
setosa       6          5.4         3.9          1.7         0.4
setosa       7          4.6         3.4          1.4         0.3
setosa       8          0.0         3.4          NaN         0.2
setosa       9          4.4         2.9          1.4         0.2
setosa      10          4.9         3.1          1.5         0.1


In [44]:
iris.isnull().head(10)

rowId  sepalLength  sepalWidth  petalLength  petalWidth
species                                                         
setosa   False        False       False        False       False
setosa   False        False       False        False       False
setosa   False        False       False        False       False
setosa   False        False       False        False       False
setosa   False        False       False        False       False
setosa   False        False       False        False       False
setosa   False        False       False        False       False
setosa   False        False       False         True       False
setosa   False        False       False        False       False
setosa   False        False       False        False       False

In [46]:
iris.notnull().head(10)

rowId  sepalLength  sepalWidth  petalLength  petalWidth
species                                                         
setosa    True         True        True         True        True
setosa    True         True        True         True        True
setosa    True         True        True         True        True
setosa    True         True        True         True        True
setosa    True         True        True         True        True
setosa    True         True        True         True        True
setosa    True         True        True         True        True
setosa    True         True        True        False        True
setosa    True         True        True         True        True
setosa    True         True        True         True        True

In [47]:
iris.isnull().sum()

rowId          0
sepalLength    0
sepalWidth     4
petalLength    4
petalWidth     0
dtype: int64

In [48]:
iris.sepalWidth.notnull().sum()

146

In [56]:
iris.isnull().sum() / iris.petalWidth.count()

rowId          0.000000
sepalLength    0.000000
sepalWidth     0.000000
petalLength    0.026667
petalWidth     0.000000
dtype: float64

In [51]:
iris.count()

rowId          150
sepalLength    150
sepalWidth     146
petalLength    146
petalWidth     150
dtype: int64

In [53]:
iris['sepalWidth'].fillna(value = iris.sepalWidth.mean(), inplace = True)

In [55]:
iris.notnull().sum()

rowId          150
sepalLength    150
sepalWidth     150
petalLength    146
petalWidth     150
dtype: int64

In [7]:
flower = iris.iloc["setosa", "sepalLength:petalLength"]


KeyError: 'the label [setosa] is not in the [index]'