## Workshop 3

### Packages and Modules

Python functions and object class definitions are bundled together in <b>modules</b>. Modules in turn are often distributed in <b>packages</b>. These packages are made available through private and public repositories. The largest and most widely used repository of python packages is <b>PyPi</b>, the Python Package Index (https://pypi.python.org/pypi).

To use a  module from any of these packages the package must first be <b><i>installed</i></b> and then the module must be <b><i>imported</i></b> into the current session.

Many of the most commonly used packages are already installed when you installed the Anaconda distribution of Python. These include <b>csv</b>, a packaged used to read in the most commonly used data file format, <b>NumPy</b>, a package that contains functions and class templates for objects useful to data science such as numeric arrays, and <b>Pandas</b>, a package that is used for a Python data structure called <i>Data Frames</i>. Another popular package is <b>MatPlotLib</b>, used to produce charts and other data visualizations.

#### csv

In [1]:
import csv

In [2]:
with open('C:/Users/Tim/Google Drive/SMU/ITOM 6267 Data Mining MSBA/data/iris.csv', newline='') as myFile:  
    reader = list(csv.reader(myFile))
    print(type(reader))
    for row in reader[0:5]:
        print(row)



<class 'list'>
['', 'sepalLength', 'sepalWidth', 'petalLength', 'petalWidth', 'species']
['1', '5.1', '3.5', '1.4', '0.2', 'setosa']
['2', '4.9', '3', '1.4', '0.2', 'setosa']
['3', '4.7', '3.2', '1.3', '0.2', 'setosa']
['4', '4.6', '3.1', '1.5', '0.2', 'setosa']


#### numpy

Now that the data has been read into the current Python session, let's do some manipulation.

In [3]:
import numpy as np

We have already seen that if we want to apply some operation like addition, multiplication or statistical calculations on multiple elements of a list we must explicitly code the calculation using element by element application in an iterative fashion using a <b><i>while</b></i> or <b><i>for</b></i> loop.

This is tedious and prone to coding errors, not to mention very inefficient when it runs. We would rather have a way to apply an operation to all or subsets of elements of an object. That's where the module <b>numpy</b> comes to the rescue.

Caveat: <b>numpy</b> creates matrix objects called <b><i>arrays</b></i>. These arrays can be of many dimensions but all elements in the array must be of the same type. So we can have an array of strings, numbers, booleans or other types.

Let's say that we want to calculate the mean of each of the columns in the iris columns. First we must extract all rows except the column labels. 

In [4]:
irisList1 = reader[1:]
print(irisList1[0:5])

[['1', '5.1', '3.5', '1.4', '0.2', 'setosa'], ['2', '4.9', '3', '1.4', '0.2', 'setosa'], ['3', '4.7', '3.2', '1.3', '0.2', 'setosa'], ['4', '4.6', '3.1', '1.5', '0.2', 'setosa'], ['5', '5', '3.6', '1.4', '0.2', 'setosa']]


Next, we run a loop to iterate over all the rows to extract only the first five numeric elements and build a new list with only those elements.

In [5]:
irisList2 = irisList1[0][1:5]
print(irisList2)

irisList2[0] = list(irisList2) # Insert a new list into irisList2
del irisList2[1:4] # Delete the "straglers"
print(irisList2)

foo = irisList1[1][1:5]
print(foo)

irisList2.append(foo)
print (irisList2)

['5.1', '3.5', '1.4', '0.2']
[['5.1', '3.5', '1.4', '0.2']]
['4.9', '3', '1.4', '0.2']
[['5.1', '3.5', '1.4', '0.2'], ['4.9', '3', '1.4', '0.2']]


Now let's replicate the above by iterating over the whole dataset.

In [6]:
for i in range(2, len(irisList1)) :
    foo = irisList1[i][1:5]
    irisList2.append(foo)
    
print(irisList2[0:3])

[['5.1', '3.5', '1.4', '0.2'], ['4.9', '3', '1.4', '0.2'], ['4.7', '3.2', '1.3', '0.2']]


Now we can write another loop that would add up all the values in each column and then divide the sums by the number of rows to yield the means for each column, a very tedious and error prone programming task. Wouldn't it be nice if we could use a single line of code to do the same thing? 

It's our lucky day. The module <b>numpy</b> is designed to do just that.

After we import numpy, we must first convert our list of lists to a two dimensional array of numeric values.

In [7]:
np_iris = np.array(irisList2)
np_iris1 = np_iris.astype(np.float)
print(type(np_iris1))
print(np_iris1.shape)
print(np_iris1[:3,:]) # Print the first 3 rows and all columns

<class 'numpy.ndarray'>
(150, 4)
[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]]


Now that we have an array of numeric decimal (nd) values, let's use some methods associated with these types of objects and see how easy it is to apply operations over many elements of the array in a single method call.

Let's start with our original goal of calculating the means of each column. 

In [8]:
meanIris = np.mean(np_iris1, axis=0) # axis = 0 means columns axis and axis = 1 means row axis
print(meanIris)

[ 5.84333333  3.05733333  3.758       1.19933333]


The same technique can be used to calculate other statistics such as sum, median, skewness, etc.

#### pandas

Now let's turn our attention to a more intuitive way of managing tabular data using the module <b>pandas</b>

In [133]:
import pandas as pd

In [163]:
iris = pd.read_csv('C:/Users/Tim/Google Drive/SMU/ITOM 6267 Data Mining MSBA/data/iris.csv')
print(type(iris))

<class 'pandas.core.frame.DataFrame'>


In [164]:
print(iris[0:5])


   Unnamed: 0  sepalLength  sepalWidth  petalLength  petalWidth species
0           1          5.1         3.5          1.4         0.2  setosa
1           2          4.9         3.0          1.4         0.2  setosa
2           3          4.7         3.2          1.3         0.2  setosa
3           4          4.6         3.1          1.5         0.2  setosa
4           5          5.0         3.6          1.4         0.2  setosa


Note that the read_csv function read in a separate column "Unnamed" populated with the row labels. We can tell python to ignore those lables with the index_col = 0 argument:

In [225]:
iris = pd.read_csv('C:/Users/Tim/Google Drive/SMU/ITOM 6267 Data Mining MSBA/data/iris.csv', index_col = 0)
print(iris[0:5])

   sepalLength  sepalWidth  petalLength  petalWidth species
1          5.1         3.5          1.4         0.2  setosa
2          4.9         3.0          1.4         0.2  setosa
3          4.7         3.2          1.3         0.2  setosa
4          4.6         3.1          1.5         0.2  setosa
5          5.0         3.6          1.4         0.2  setosa


What type of object is iris?

In [226]:
type(iris)

pandas.core.frame.DataFrame

We see that iris is a pandas DataFrame. It is conveniently organized as a rectangular table with row and column headers. This makes it easy to analyze data by slices in both row and column dimensions, aka, "slice and dice". Let's start with a calculation on a single column.

In [227]:
iris.sepalLength.mean() # numeric column

5.843333333333335

In [228]:
iris['species'].value_counts(dropna = False) # categorical column

setosa        50
versicolor    50
virginica     50
Name: species, dtype: int64

Multiple metrics can be calculated with the <i>agg</i> modifier.

In [168]:
iris.sepalLength.agg(['count', 'mean', 'std'])

count    150.000000
mean       5.843333
std        0.828066
Name: sepalLength, dtype: float64

A <i>groupby</i> modifier can be used to calculate a metric by some categorical column.

In [170]:
iris.groupby('species').sepalLength.mean()

species
setosa        5.006
versicolor    5.936
virginica     6.588
Name: sepalLength, dtype: float64

We can even calculate multiple metrics with the <i>agg</i> modifier grouped by some categorical column.

In [229]:
iris.groupby('species').sepalLength.agg(['count','mean', 'std', 'skew'])

count   mean       std      skew
species                                     
setosa         50  5.006  0.352490  0.120087
versicolor     50  5.936  0.516171  0.105378
virginica      50  6.588  0.635880  0.118015

Another very powerful use of groupby is that we don't have to specify any particular column to aggregate. This is particularly useful if we don't have very many numeric columns to calculate on.

In [230]:
iris.groupby('species').mean()

sepalLength  sepalWidth  petalLength  petalWidth
species                                                     
setosa            5.006       3.428        1.462       0.246
versicolor        5.936       2.770        4.260       1.326
virginica         6.588       2.974        5.552       2.026

Pandas subsets can also be extracted with square brackets but there are two methods that are particularly powerful: loc and iloc. loc uses labels and iloc uses integer indices.

Let's start with extracting all the rows for the species versicolor.

In [231]:
irisVersicolor = iris.loc[iris.species == 'versicolor', :]
print(irisVersicolor.head())

    sepalLength  sepalWidth  petalLength  petalWidth     species
51          7.0         3.2          4.7         1.4  versicolor
52          6.4         3.2          4.5         1.5  versicolor
53          6.9         3.1          4.9         1.5  versicolor
54          5.5         2.3          4.0         1.3  versicolor
55          6.5         2.8          4.6         1.5  versicolor


Another powerful feature of pandas is that we can specify any column as the index column.

In [232]:
iris = pd.read_csv('C:/Users/Tim/Google Drive/SMU/ITOM 6267 Data Mining MSBA/data/iris.csv', index_col = 'species')
print(iris[0:5])

         Unnamed: 0  sepalLength  sepalWidth  petalLength  petalWidth
species                                                              
setosa            1          5.1         3.5          1.4         0.2
setosa            2          4.9         3.0          1.4         0.2
setosa            3          4.7         3.2          1.3         0.2
setosa            4          4.6         3.1          1.5         0.2
setosa            5          5.0         3.6          1.4         0.2


Now we can use loc to select rows using the index_column.

In [233]:
irisSetosa = iris.loc['setosa', 'sepalLength':'petalWidth']
print(irisSetosa.head())

         sepalLength  sepalWidth  petalLength  petalWidth
species                                                  
setosa           5.1         3.5          1.4         0.2
setosa           4.9         3.0          1.4         0.2
setosa           4.7         3.2          1.3         0.2
setosa           4.6         3.1          1.5         0.2
setosa           5.0         3.6          1.4         0.2


In [234]:
irisSetosa.count()

sepalLength    50
sepalWidth     50
petalLength    50
petalWidth     50
dtype: int64

iloc is used to select using the usual integer index.

In [235]:
print(irisSetosa.iloc[0:3, 0:5])

         sepalLength  sepalWidth  petalLength  petalWidth
species                                                  
setosa           5.1         3.5          1.4         0.2
setosa           4.9         3.0          1.4         0.2
setosa           4.7         3.2          1.3         0.2


#### Missing Values

Pandas has some great methods that help us detect and treat missing values.

In [236]:
iris = pd.read_csv('C:/Users/Tim/Google Drive/SMU/ITOM 6267 Data Mining MSBA/data/iris_missing.csv', index_col = 'species')
print(iris.head(10))

         rowId  sepalLength  sepalWidth  petalLength  petalWidth
species                                                         
setosa       1          5.1         3.5          1.4         0.2
setosa       2          4.9         3.0          1.4         0.2
setosa       3          4.7         3.2          1.3         0.2
setosa       4          4.6         3.1          1.5         0.2
setosa       5          5.0         3.6          1.4         0.2
setosa       6          5.4         3.9          1.7         0.4
setosa       7          4.6         3.4          1.4         0.3
setosa       8          0.0         3.4          NaN         0.2
setosa       9          4.4         2.9          1.4         0.2
setosa      10          4.9         3.1          1.5         0.1


In [237]:
iris.isnull().head(10)

rowId  sepalLength  sepalWidth  petalLength  petalWidth
species                                                         
setosa   False        False       False        False       False
setosa   False        False       False        False       False
setosa   False        False       False        False       False
setosa   False        False       False        False       False
setosa   False        False       False        False       False
setosa   False        False       False        False       False
setosa   False        False       False        False       False
setosa   False        False       False         True       False
setosa   False        False       False        False       False
setosa   False        False       False        False       False

In [238]:
iris.notnull().head(10)

rowId  sepalLength  sepalWidth  petalLength  petalWidth
species                                                         
setosa    True         True        True         True        True
setosa    True         True        True         True        True
setosa    True         True        True         True        True
setosa    True         True        True         True        True
setosa    True         True        True         True        True
setosa    True         True        True         True        True
setosa    True         True        True         True        True
setosa    True         True        True        False        True
setosa    True         True        True         True        True
setosa    True         True        True         True        True

In [239]:
iris.notnull().sum()

rowId          150
sepalLength    150
sepalWidth     146
petalLength    146
petalWidth     150
dtype: int64

In [240]:
iris.petalLength.notnull().sum()

146

In [241]:
iris.isnull().sum() / iris.count() # Calculate percent missing

rowId          0.000000
sepalLength    0.000000
sepalWidth     0.027397
petalLength    0.027397
petalWidth     0.000000
dtype: float64

Now that we know that there are missing values. Let's impute them with the mean values of the columns.

In [250]:
iris['sepalWidth'].fillna(value = iris.sepalWidth.mean(), inplace = True)
iris['petalLength'].fillna(value = iris.petalLength.mean(), inplace = True)

In [251]:
iris.notnull().sum()


rowId          150
sepalLength    150
sepalWidth     150
petalLength    150
petalWidth     150
dtype: int64